//for only admins
export const GET_TEAMS_EARNING_REPORT = 'TH.GET_TEAMS_EARNING_REPORT'
export const GET_SELECTED_TEAM_EARNING_REPORT = 'TH.GET_SELECTED_TEAM_EARNING_REPORT'
//for both admins and team-managers
export const GET_TOTAL_EARNING_REPORT = 'TH.GET_TOTAL_EARNING'
export const GET_DEVELOPERS_EARNING_REPORT = 'TH.GET_DEVELOPERS_EARNING_REPORT'
export const GET_INDIVIDUAL_DEVELOPER_EARNING_REPORT = 'TH.GET_INDIVIDUAL_DEVELOPER_EARNING_REPORT'
export const GET_INDIVIDUAL_DEVELOPER_PROJECT_EARNING_REPORT = 'TH.GET_INDIVIDUAL_DEVELOPER_PROJECT_EARNING_REPORT'
//for only developers
export const GET_SELF_FINANCIAL_REPORT = 'TH.GET_SELF_FINANCIAL_REPORT'
