//for only admins
export const GET_TEAMS_EARNING_REPORT = 'TH.GET_TEAMS_EARNING_REPORT'
export const GET_SELECTED_TEAM_EARNING_REPORT = 'TH.GET_SELECTED_TEAM_EARNING_REPORT'
//for both admins and team-managers
export const GET_TOTAL_EARNING_REPORT = 'TH.GET_TOTAL_EARNING'
export const GET_DEVELOPERS_EARNING_REPORT = 'TH.GET_DEVELOPERS_EARNING_REPORT'
export const GET_INDIVIDUAL_DEVELOPER_EARNING_REPORT = 'TH.GET_INDIVIDUAL_DEVELOPER_EARNING_REPORT'
export const GET_INDIVIDUAL_DEVELOPER_PROJECT_EARNING_REPORT = 'TH.GET_INDIVIDUAL_DEVELOPER_PROJECT_EARNING_REPORT'
//for only developers
export const GET_SELF_EARNING_REPORT = 'TH.GET_SELF_EARNING_REPORT'
export const GET_SELF_PROJECT_EARNING_REPORT = 'TH.GET_SELF_PROJECT_EARNING_REPORT'

//for download
export const DOWNLOAD_DEVELOPERS_EARNING = 'TH.DOWNLOAD_DEVELOPERS_EARNING'
export const DOWNLOAD_INDIVIDUAL_DEVELOPER_EARNING = 'TH.DOWNLOAD_INDIVIDUAL_DEVELOPER_EARNING'
export const DOWNLOAD_INDIVIDUAL_DEVELOPER_PROJECTS_EARNING = 'TH.DOWNLOAD_INDIVIDUAL_DEVELOPER_PROJECTS_EARNING'
export const DOWNLOAD_TEAMS_EARNING = 'TH.DOWNLOAD_TEAMS_EARNING'
export const DOWNLOAD_SELECTED_TEAM_EARNING = 'TH.DOWNLOAD_SELECTED_TEAM_EARNING'

export const DOWNLOAD_MY_REPORT = 'TH.DOWNLOAD_MY_REPORT'
