export const GET_INDIVIDUALREPORT = 'TH.GET_INDIVIDUALREPORT'
export const GET_MY_REPORT = 'TH.GET_MY_REPORT'
export const GET_TEAMREPORT = 'TH.GET_TEAMREPORT'
export const GET_MY_TEAM_REPORTS = 'TH.GET_MY_TEAM_REPORTS'
