export const GET_DAILY_LOGS = 'TH.GET_DAILY_LOGS'
export const GET_DAILY_LOG_DETAIL = 'TH.GET_DAILY_LOG_DETAIL'
export const GET_MONTHLY_LOGS = 'TH.GET_MONTHLY_LOGS'
export const GET_MONTHLY_LOG_DETAIL = 'TH.GET_MONTHLY_LOG_DETAIL'
