export const GET_TRANSACTIONS = 'TH.GET_TRANSACTIONS'
export const GET_TRANSACTION_DETAIL = 'TH.GET_TRANSACTION_DETAIL'

//for download
export const DOWNLOAD_TRANSACTIONS = 'TH.DOWNLOAD_TRANSACTIONS'

export const CREATE_TRANSACTION = 'TH.CREATE_TRANSACTION'
export const DELETE_TRANSACTION = 'TH.DELETE_TRANSACTION'
export const DELETE_TRANSACTION_AND_REFRESH = 'TH.DELETE_TRANSACTION_AND_REFRESH'
export const UPDATE_TRANSACTION = 'TH.UPDATE_TRANSACION'
