export const GET_TRANSACTIONS = 'TH.GET_TRANSACTIONS'
export const GET_TRANSACTION_DETAIL = 'TH.GET_TRANSACTION_DETAIL'

//for download
export const DOWNLOAD_TRANSACTIONS = 'TH.DOWNLOAD_TRANSACTIONS'
