export const AUTH_LOGIN = 'TH.AUTH_LOGIN'
export const AUTH_SIGNUP = 'TH.AUTH_SIGNUP'
export const AUTH_LOGOUT = 'TH.AUTH_LOGOUT'
export const AUTH_GETME = 'TH.AUTH_GETME'
export const AUTH_UPDATEME = 'TH.AUTH_UPDATEME'
export const AUTH_FAIL = 'TH.AUTH_FAIL'
export const AUTH_SUCCESS = 'TH.AUTH_SUCCESS'
