export const GET_MY_Daily_LOG = 'TH.GET_MY_Daily_LOG'
export const CREATE_MY_Daily_LOG = 'TH.CREATE_MY_Daily_LOG'
export const UPDATE_MY_Daily_LOG = 'TH.UPDATE_MY_Daily_LOG'
export const GET_MY_MONTHLY_LOG = 'TH.GET_MY_MONTHLY_LOG'
export const CREATE_MY_MONTHLY_LOG = 'TH.CREATE_MY_MONTHLY_LOG'
export const UPDATE_MY_MONTHLY_LOG = 'TH.CREATE_MY_MONTHLY_LOG'
